services:
  - type: web
    name: aurore-bot
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: INTERNAL_TOKEN
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://frontend-teal-eight-79.vercel.app
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
